ingressClass: merge
configmapSelector: ""
ingressSelector: ""
configmapBlacklist: []
ingressBlacklist: []

rbac:
  create: true
  serviceAccountName: default

image:
  repository: jakubkulhan/ingress-merge
  tag: latest
  pullPolicy: Always

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
